# Generated by Django 5.2.4 on 2025-07-29 10:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_books_translator'),
        ('user', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookimage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.RemoveField(
            model_name='star',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.author'),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=-2012, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=-2012, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.basemodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.basemodel')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='book.books')),
            ],
            bases=('book.basemodel',),
        ),
    ]
