# Generated by Django 5.2.4 on 2025-07-30 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_basemodel_remove_bookimage_id_and_more'),
        ('user', '0004_translator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
        migrations.RemoveField(
            model_name='books',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='books',
            name='book_language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('en', 'English'), ('ru', 'Russian'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('fr', 'French')], default='uz', max_length=10),
        ),
        migrations.AlterField(
            model_name='books',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.translator'),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.basemodel')),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('psychology_and_personal_development', 'Psychology and personal development'), ('business', 'Business'), ('Children_literature', "Children's literature"), ('religious_literature', 'Religious literature'), ('books_in_russian', 'Books in Russian'), ('sducational_literature', 'Educational literature'), ('top_100_bestsellers', 'TOP-100 bestsellers'), ('bestseller_sets', 'Bestseller sets'), ('detective', 'Detective'), ('science_fiction', 'Science Fiction'), ('politics', 'Politics'), ('biography', 'Biography'), ('book_gift_sets', 'Book gift sets'), ('turkish_literature', 'Turkish literature'), ('history', 'History'), ('books_in_english', 'Books in English'), ('books_for_collectors', 'Books for collectors')], max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='book.books')),
            ],
            options={
                'unique_together': {('book', 'category')},
            },
            bases=('book.basemodel',),
        ),
    ]
