# Generated by Django 5.2.4 on 2025-07-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_price_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_sum',
        ),
    ]
